### ISSUE TITLE
TunerStudio (TCP) Mode does not work

### ISSUE THREAD

**Issue by Bolino08C** [speeduino/Airbear#5]
Hi, 

I tested the Airbear firmware but when I use TunerStudio TCP mode it doesn't work.

OTA => Ok
Bluetooth BLE => Ok

In the USB log, the esp32c3 tells me that  : Core dump flash config is corrupted!

The log :
--------------

Config Initialised
40597285699530
No values saved for ssid or password. Starting AP mode.
0.0.0.0
Connection Type: 3
New client has been connected to TCP socket, ip: 192.168.4.2 
TunerStudio Requests received: 0
1 bytes received from client 192.168.4.2: F
E (12101) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (12101) task_wdt:  - async_tcp (CPU 0)
E (12101) task_wdt: Tasks currently running:
E (12101) task_wdt: CPU 0: async_tcp
E (12101) task_wdt: Aborting.

abort() was called at PC 0x4203c277 on core 0
Core  0 register dump:
MEPC    : 0x403825cc  RA      : 0x4038a7a0  SP      : 0x3fc98640  GP      : 0x3fc92600  
TP      : 0x3fc9f960  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  
S0/FP   : 0x3fc9866c  S1      : 0x3fc9866c  A0      : 0x3fc98678  A1      : 0x3fc9865a  
A2      : 0x00000000  A3      : 0x3fc986a5  A4      : 0x00000001  A5      : 0x3fc9d000  
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x3fc9c950  S3      : 0x7fffffff  
S4      : 0x3fc93cec  S5      : 0x3fc93cdc  S6      : 0x3fc93ce4  S7      : 0x3fc93cdc  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938  
MSTATUS : 0x00001801  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
MHARTID : 0x00000000  

Stack memory:
3fc98640: 0x00000000 0x00000000 0x3fc98658 0x4039065c 0x3fc93ce4 0x3fc93cdc 0x3fc90030 0x3fc950f8
3fc98660: 0x3fc9866c 0x3fc95114 0x3fc98658 0x33303234 0x37373263 0x00000000 0x726f6261 0x20292874
3fc98680: 0x20736177 0x6c6c6163 0x61206465 0x43502074 0x34783020 0x63333032 0x20373732 0x63206e6f
3fc986a0: 0x2065726f 0x00000030 0x3c0f0000 0x1c5ed342 0x600c2000 0x3c0fb000 0x3fc9d000 0x4203c27a
3fc986c0: 0x3fce0000 0x40383db2 0x3fce0000 0x00002f45 0x4206305e 0x3fce0000 0x3c107424 0x3fcc444b
3fc986e0: 0x3fc9d000 0x3fcc444a 0x3fc97000 0x00000001 0x00001881 0x80000007 0x3fc9c8f4 0x403801ee
3fc98700: 0x00000001 0x3fc98708 0xffffffff 0x3fca1ed4 0x3fca1ed4 0x00000001 0x3fc9871c 0xffffffff
3fc98720: 0x3fca4f00 0x3fca4f00 0x00000000 0x3fc98730 0xffffffff 0x3fc98730 0x3fc98730 0x00000001
3fc98740: 0x3fc98744 0xffffffff 0x3fcbdfd8 0x3fcbdfd8 0x00000000 0x3fc98758 0xffffffff 0x3fc98758
3fc98760: 0x3fc98758 0x00000000 0x3fc9876c 0xffffffff 0x3fc9876c 0x3fc9876c 0x00000000 0x3fc98780
3fc98780: 0xffffffff 0x3fc98780 0x3fc98780 0x00000000 0x3fc98794 0xffffffff 0x3fc98794 0x3fc98794
3fc987a0: 0x00000000 0x3fc987a8 0xffffffff 0x3fc987a8 0x3fc987a8 0x00000000 0x3fc987bc 0xffffffff
3fc987c0: 0x3fc987bc 0x3fc987bc 0x00000000 0x3fc987d0 0xffffffff 0x3fc987d0 0x3fc987d0 0x00000000
3fc987e0: 0x3fc987e4 0xffffffff 0x3fc987e4 0x3fc987e4 0x00000000 0x3fc987f8 0xffffffff 0x3fc987f8
3fc98800: 0x3fc987f8 0x00000000 0x3fc9880c 0xffffffff 0x3fc9880c 0x3fc9880c 0x00000000 0x3fc98820
3fc98820: 0xffffffff 0x3fc98820 0x3fc98820 0x00000000 0x3fc98834 0xffffffff 0x3fc98834 0x3fc98834
3fc98840: 0x00000000 0x3fc98848 0xffffffff 0x3fc98848 0x3fc98848 0x00000000 0x3fc9885c 0xffffffff
3fc98860: 0x3fc9885c 0x3fc9885c 0x00000000 0x3fc98870 0xffffffff 0x3fc98870 0x3fc98870 0x00000000
3fc98880: 0x3fc98884 0xffffffff 0x3fc98884 0x3fc98884 0x00000000 0x3fc98898 0xffffffff 0x3fc98898
3fc988a0: 0x3fc98898 0x00000000 0x3fc988ac 0xffffffff 0x3fc988ac 0x3fc988ac 0x00000000 0x3fc988c0
3fc988c0: 0xffffffff 0x3fc988c0 0x3fc988c0 0x00000000 0x3fc988d4 0xffffffff 0x3fc988d4 0x3fc988d4
3fc988e0: 0x00000000 0x3fc988e8 0xffffffff 0x3fc988e8 0x3fc988e8 0x00000001 0x3fc988fc 0xffffffff
3fc98900: 0x3fcb2edc 0x3fcb2edc 0x00000000 0x3fc98910 0xffffffff 0x3fc98910 0x3fc98910 0x00000000
3fc98920: 0x3fc98924 0xffffffff 0x3fc98924 0x3fc98924 0x00000008 0x3fc98938 0xffffffff 0x3fcb1748
3fc98940: 0x3fcabc9c 0x00000000 0x3fc9894c 0xffffffff 0x3fc9894c 0x3fc9894c 0x00000003 0x00000000
3fc98960: 0x3fcb18a8 0x3fcb167c 0x00000004 0x00000001 0x3fcb18a8 0x3fcb167c 0x00000002 0x0000002f
3fc98980: 0x3fcb18a8 0x3fcb167c 0x00000003 0x00000000 0x3fcb06fc 0x00000000 0x00000003 0x00000000
3fc989a0: 0x3fcb18a8 0x00000000 0x00000004 0x00000064 0x3fcb18a8 0x00000000 0x00000002 0x0000002f
3fc989c0: 0x3fcb18a8 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fc989e0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x3fc98a00
3fc98a00: 0xffffffff 0x3fc98a00 0x3fc98a00 0x00000000 0x3fc98a14 0xffffffff 0x3fc98a14 0x3fc98a14
3fc98a20: 0x3fc98958 0x3fc989c8 0x3fc989f8 0x3fc989b8 0x00000000 0x3fc98a38 0xffffffff 0x3fc98a38

ELF file SHA256: 42c410e1e27adc69

E (11440) esp_core_dump_flash: Core dump flash config is corrupted! CRC=0x7bd5c66f instead of 0x0
Rebooting...
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0xf (SPI_FAST_FLASH_BOOT)
Saved PC:0x403821ce
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5810,len:0x438
load:0x403cc710,len:0x90c
load:0x403ce710,len:0x2624
entry 0x403cc710
E (193) esp_core_dump_flash: No core dump partition found!
E (193) esp_core_dump_flash: No core dump partition found!

**Comment by noisymime** [comment]
The TCP mode requires you to have the latest master firmware on your ECU and select the 'TunerStudio" protocol in the secondary comms list. 

How do you have your ECU set up?

**Comment by Bolino08C** [comment]
Ok 
Actually, I don't have the latest master firmware. (V2024.02.1)
I hadn't seen the addition of the Tunerstudio option in the master firmware.
I tested the protocols (with v2024.02.1): 
Generic (Fixed List) => Web Dash Ok 
And msDroid.

**Comment by noisymime** [comment]
Closing as this requires latest firmware
